//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseLibs.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinAccount
    {
        public long SNo { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string UserId { get; set; }
        public string LoginStatus { get; set; }
        public string LogoSource { get; set; }
        public string Bio { get; set; }
        public string Session { get; set; }
    }
}
