//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseLibs.DBUtility.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebHeader
    {
        public long SNo { get; set; }
        public string MainUrl { get; set; }
        public string PageUrl { get; set; }
        public string PageUrlFormat { get; set; }
        public string PostData { get; set; }
        public string PostDataFormat { get; set; }
        public string HeaderType { get; set; }
        public string HeaderWithValues { get; set; }
        public string Referer { get; set; }
        public string TokenFormat { get; set; }
        public string RefererFormat { get; set; }
        public string Token { get; set; }
        public string OtherField1 { get; set; }
        public string OtherField1Format { get; set; }
        public string OtherField2 { get; set; }
        public string OtherField2Format { get; set; }
        public string OtherField3 { get; set; }
        public string OtherField3Format { get; set; }
    }
}
